### ISSUE TITLE
ECDSACoin: get_owner doesn't work after retrieving coin from disk

### ISSUE THREAD

**Issue by SamSamskies** [justinmoon/digital-cash#4]
Steps to recreate bug:
1. Create a coin with Alice's public key
2. Save to disk
3. Retrieve coin from disk
4. Run get_owner with that coin

This bug is fixed by serializing the keys in get_owner. See below:
```python
def get_owner(coin):
    database = {
        serialize(bob_public_key): "Bob",
        serialize(alice_public_key): "Alice",
        serialize(bank_public_key): "Bank"
    }
    public_key = serialize(coin.transfers[-1].public_key)

    return database[public_key]
```

**Comment by justinmoon** [comment]
Thanks for this. Fixed by https://github.com/justinmoon/digital-cash/commit/9f44a85dde64620a49d319388003ce538365fe34#diff-eaf45354a1dc8df9f543a080468a9e42R229!
